spring:
  application:
    name: user-service

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topic:
    user-random-topic: user-random-topic
    user-created-topic: user-created-topic

  kafka:
    producer:
      properties:
        spring.json.add.type.headers: false  # Disable automatic type headers
